name: 'Emby Plugin'

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6
      - name: Restore NuGet Packages
        run: dotnet restore
      - name: .NET Publish
        run: dotnet publish --configuration Release --output publish Emby.Plugin.Bangumi
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Emby.Plugin.Bangumi
          path: publish/Emby.Plugin.Bangumi.dll
